Updates
* Removed dead hosts (ptpb, mixtape, lewd, doko).
Lewd.se host isn't actually dead, but it's now login-only.
There's no plan to add auth support for the said host.

* Fixed URL parsing for waaai shortener.

* Using -c option will now copy the screenshots to clipboard BEFORE
saving (if using -p) and uploading them.

* Using -c option will now still display notification containing the
uploaded screenshot's URL.

* Show usage ONLY if no actions were used (-f, -l, -s, -u <file>, -w),
instead of merely checking whether at least one argument was used.
Also show a different error message when using fiery-exclusive options
(-a, -t, -D) with no actions.

diff --git a/uguush b/uguush
--- a/uguush
+++ b/uguush
@@ -40,7 +40,7 @@ delaySeconds='0'
 # hosts and shorteners
 host='fiery'
 shortener=
-hosts='uguu 0x0 ptpb mixtape lewd fiery doko'
+hosts='uguu 0x0 fiery'
 shorteners='waaai 0x0'
 
 ## FUNCTIONS
@@ -65,7 +65,7 @@ Options:
 	-d		Delay the screenshot by the specified number of seconds.
 	-f		Take a fullscreen screenshot.
 	-h		Show this help message.
-	-o <host>	Select which host to use (uguu, 0x0, ptpb, mixtape, lewd, fiery or doko).
+	-o <host>	Select which host to use (uguu, 0x0 or fiery).
 	-p <path>	Custom path to save the image to. Saves the image as "%Y-%m-%d %H-%M-%S.png".
 	-c		Copy image instead of URL to clipboard.
 	-n		Enable save notification (if used alongside -p option).
@@ -73,7 +73,7 @@ Options:
 	-u <file>	Upload a file.
 	-x		Do not notify dbus, update the log, or modify the clipboard.
 	-w		Take a screenshot of the current window.
-	-S		Select a shortener to use. Can be waaai or 0x0.
+	-S		Select a shortener to use (waaai or 0x0).
 	-l <url>	Upload the file at the provided URL.
 	-k		Use KDE/Spectacle (with -p file name will be "Screenshot_%Y%m%d_%H%M%S.png").
 	-t <token>	Set token (for fiery host).
@@ -107,7 +107,7 @@ screenshot() {
 		screenshotWindow="scrot -u"
 	elif [ "${doFullscreen}" ] || [ "${doSelection}" ] || [ "${doWindow}" ]; then
 		echo "Checking for a screenshot utility... [${c1}FAILED${c0}]" >&2
-		echo "could not find a screenshot utility, please install 'maim' or 'scrot'" >&2
+		echo "Could not find a screenshot utility, please install 'maim' or 'scrot'" >&2
 		if [ -f "${localTemp}" ]; then rm "${localTemp}"; fi
 		exit 1
 	fi
@@ -146,32 +146,17 @@ upload() {
 		case "${host}" in
 			0x0) hostURL='https://0x0.st/' ;;
 			uguu) hostURL='https://uguu.se/api.php?d=upload-tool' ;;
-			ptpb) hostURL='https://ptpb.pw/' ;;
-			mixtape) hostURL='https://mixtape.moe/upload.php' ;;
-			lewd) hostURL='https://lewd.se/api.php?d=upload-tool' ;;
 			fiery) hostURL='https://safe.fiery.me/api/upload' ;;
-			doko) hostURL='https://doko.moe/upload.php' ;;
 		esac
 
 		case "${shortener}" in
 			waaai) shortenerURL='https://api.waa.ai/shorten' ;;
 			0x0) shortenerURL='http://0x0.st/' ;;
-			ptpb) shortenerURL='https://ptpb.pw/u' ;;
 		esac
 
 		if [ "${host}" = 'uguu' ]; then
 			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
 		elif [ "${host}" = '0x0' ]; then
-			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
-		elif [ "${host}" = 'mixtape' ]; then
-			uploadResult="$(curl -sf -F files[]="@${localFile}" "${hostURL}")"
-			uploadResult="$(echo "${uploadResult}" | grep -Po '"url":"[A-Za-z0-9]+.*?"' | sed 's/"url":"//;s/"//')"
-			uploadResult="$(echo "${uploadResult}" | sed 's/\\//g')"
-		elif [ "${host}" = 'ptpb' ]; then
-			uploadResult="$(curl -sf -F c="@${localFile}" "${hostURL}")"
-			uploadResult="${uploadResult##*url: }"
-			uploadResult="${uploadResult%%$'\n'*}"
-		elif [ "${host}" = 'lewd' ]; then
 			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
 		elif [ "${host}" = 'fiery' ]; then
 			uploadResult="$(curl -H "token: ${fieryToken}" -H "albumid: ${fieryAlbumId}" -sf -F files[]="@${localFile}" "${hostURL}")"
@@ -179,10 +164,6 @@ upload() {
 			if [ "${fieryDomain}" ]; then
 				uploadResult="$(echo "${uploadResult}" | sed "s/i.fiery.me/${fieryDomain}/")"
 			fi
-		elif [ "${host}" = 'doko' ]; then
-			uploadResult="$(curl -sf -F files[]="@${localFile}" "${hostURL}")"
-			uploadResult="$(echo "${uploadResult}" | grep -Po '"url":"[A-Za-z0-9]+.*?"' | sed 's/"url":"//;s/"//')"
-			uploadResult="$(echo "${uploadResult}" | sed 's/\\//g')"
 		fi
 
 		if [ "${shortener}" = 'waaai' ]; then
@@ -190,8 +171,9 @@ upload() {
 			shortCode="${tempResult##*short_code\":\"}"
 			shortCode="${shortCode%%\"*}"
 			shortenerResult="https://waa.ai/${shortCode}"
-			shortenerExtension="${tempResult##*extension\":}"
-			shortenerExtension="${shortenerExtension%%\}*}"
+			shortenerExtension="${tempResult##*extension\":\"}"
+			shortenerExtension="${shortenerExtension%%\"*}"
+			echo "${shortenerExtension}"
 			if [ "${shortenerExtension}" ]; then
 				shortenerExtension=${shortenerExtension##\"}
 				shortenerExtension=${shortenerExtension%%\"}
@@ -199,8 +181,6 @@ upload() {
 			fi
 		elif [ "${shortener}" = '0x0' ]; then
 			shortenerResult="$(curl -sf -F shorten="${uploadResult}" "${shortenerURL}")"
-		elif [ "${shortener}" = 'ptpb' ]; then
-			shortenerResult="$(curl -sf -F c=@- "${shortenerURL}" <<< "${uploadResult}")"
 		fi
 
 		if [ "${shortener}" ]; then
@@ -210,32 +190,20 @@ upload() {
 		fi
 
 		if [ "${?}" = 0 ]; then
-
 			# copy to clipboard, log, and notify (unless $noComms is set)
 			if [ ! "${noComms}" ]; then
-
-				# copy image to clipboard
 				if [ "${copyImage}" = 'true' ]; then
-					mimeType=$(file -b --mime-type "$localFile")
-					xclip -selection primary -t "$mimeType" < "$localFile"
-					xclip -selection clipboard -t "$mimeType" < "$localFile"
-					notifyMessage="Image copied to clipboard"
-					notifyIcon="edit-copy"
+					notify-send "uguu~" "Link to screenshot: ${finalResult}" -h string:x-canonical-private-synchronous:uguush -i "link"
 				else
 					echo -n "${finalResult}" | xclip -selection primary
 					echo -n "${finalResult}" | xclip -selection clipboard
-					notifyMessage="Link copied to clipboard: '${finalResult}'"
-					notifyIcon="url-copy"
+					notify-send "uguu~" "Link copied to clipboard: ${finalResult}" -h string:x-canonical-private-synchronous:uguush -i "url-copy"
 				fi
-
-				echo "$(date +"%D %R") | "${file}" | "${finalResult}"" >> ~/.uguush.log
-				notify-send "uguu~" "${notifyMessage}" -h string:x-canonical-private-synchronous:uguush -i "$notifyIcon"
-
 			fi
+			echo "$(date +"%D %R") | "${file}" | "${finalResult}"" >> ~/.uguush.log
+			echo "[${c2}OK${c0}]"
+			echo "File has been uploaded: ${finalResult}"
 		fi
-
-		echo "[${c2}OK${c0}]"
-		echo "File has been uploaded: ${finalResult}"
 
 		# if we took a screenshot, remove the temporary file
 		if [ -z "${doFile}" ]; then
@@ -243,8 +211,16 @@ upload() {
 		fi
 
 		exit
-
 	done
+}
+
+copyimage() {
+	if [ ! "${noComms}" ] && [ "${copyImage}" = 'true' ]; then
+		mimeType=$(file -b --mime-type "$localFile")
+		xclip -selection primary -t "$mimeType" < "$localFile"
+		xclip -selection clipboard -t "$mimeType" < "$localFile"
+		notify-send "uguu~" "Screenshot copied to clipboard" -h string:x-canonical-private-synchronous:uguush -i "edit-copy"
+	fi
 }
 
 path() {
@@ -329,7 +305,7 @@ while getopts :a:cd:fhikl:no:p:st:u:wxD:S: opt ;do
 			localFile="${OPTARG}"
 			if [ ! -f "${localFile}" ]; then
 				echo "Checking for file... [${c1}FAILED${c0}]" >&2
-				echo 'file not found.' >&2
+				echo 'File not found.' >&2
 				exit 1
 			fi ;;
 		w)
@@ -358,9 +334,18 @@ while getopts :a:cd:fhikl:no:p:st:u:wxD:S: opt ;do
 	esac
 done
 
-# show usage if no arguments are given
-if [ "$#" -lt 1 ]; then
-	usage
+# show usage if no action is chosen
+if [ ! "${doFullscreen}" ] && [ ! "${doURL}" ] && [ ! "${doSelection}" ] && [ ! "${doFile}" ] && [ ! "${doWindow}" ]; then
+
+	if [ "${fieryAlbumId}" ] || [ "${fieryToken}" ] || [ "${fieryDomain}" ]; then
+		echo "Fiery-exclusive options must be used during screenshots.
+
+Example: $(basename "${0}") -t TOKEN_HERE -s
+to take a selection screenshot and upload to fiery host using the token." >&2
+	else
+		usage
+	fi
+
 	exit 1
 fi
 
@@ -369,6 +354,7 @@ fi
 depends
 delay
 screenshot
+copyimage
 path
 upload
 
